#Terminologies in Tuple...

# 1. Immutable : Tuples are not mutable, you cannot change the values of tuple...

# 2. Duplicates : You can have duplicate values in tuple, there are no restriction...

# 3. Ordered : Set are ordered and you can access them through index values...

# 4. Heterogenous : Set also have heterogenous nature and can have different types of data structure in tuple...

#Syntax of Tuple...

a = (1, 2, 3, 4, 5) #parantheses are used to represent the tuples...
print(type(a))


#Traversing in Tuple...

#Tuples are traversed in the same manner as List are traversed...
# But remember tuples are like strings you can't change anything once it's made we can't change them...


